services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/static:/app/static
      - ./backend/face_recognition.db:/app/face_recognition.db
    ports:
      - "8000:8000"
    environment:
      - API_URL=http://backend:8000

  frontend:
    build:
      context: ./frontend/facedetection
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
